# Generated by Django 3.0.7 on 2020-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='sno',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
