# Generated by Django 3.0.7 on 2020-06-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_app',
        ),
    ]
